Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    


а) произведения матриц не определены

б) $AB$ - матрица $2\times 3$

$BA$ - произведение матриц не определено

в) $AB$ - матрица $8\times 8$

$BA$ - матрица $3\times 3$

г) матрицы $4\times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

    


In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], 
              [3, 0]])
B = np.array([[4, -1], 
              [0, 5]])

$$A + B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
5  & -3 \\
3  & 5
\end{pmatrix}$$


In [3]:
A+B

array([[ 5, -3],
       [ 3,  5]])

$$A \times B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \times \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 \cdot 4 + (-2) \cdot 0 & 1 \cdot (-1) + (-2) \cdot 5 \\
3 \cdot (4) + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5
\end{pmatrix} = \begin{pmatrix}
4 & -11 \\
12 & -3
\end{pmatrix}
$$


In [4]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

$$B \times A = 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \times \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = \begin{pmatrix}
4 \cdot 1 + (-1) \cdot 3 & 4 \cdot (-2) + (-1) \cdot 0 \\
0 \cdot 1 + 5 \cdot 3 & 0 \cdot (-2) + 5 \cdot 0
\end{pmatrix} = \begin{pmatrix}
1 & -8 \\
15 & 0
\end{pmatrix}
$$


In [5]:
np.dot(B, A)

array([[ 1, -8],
       [15,  0]])


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$3A-2B+4C = 3 \times \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2 \times \begin{pmatrix}
0 & 5\\ 
2 & -1 
\end{pmatrix} + 4 \times \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix} 
3 \cdot 1 - 2 \cdot 0 + 4 \cdot 2 & 3 \cdot 7 - 2 \cdot 5 + 4 \cdot (-4) \\
3 \cdot 3 - 2 \cdot 2 + 4 \cdot 1 & 3 \cdot (-6) - 2 \cdot (-1) + 4 \cdot 1
\end{pmatrix} = \begin{pmatrix} 
11 & -5 \\
9 & -12
\end{pmatrix}  
$$


In [6]:
A = np.array([[1, 7],
              [3, -6]])
B = np.array([[0, 5],
              [2, -1]])
C = np.array([[2, -4],
              [1, 1]])

In [7]:
(3*A) + (-2*B) + (4*C)

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$$A^{T}=\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix}$$

$$A \times A^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix} 
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3\\
5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) &  5 \cdot 2 + (-2) \cdot 3 \\
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix} 
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}$$


$$A^{T} \times A =  \begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix} 
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3 \\
1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2 & 1 \cdot 1 + (-2) \cdot (-2) + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix} 
45 & 0 \\
0 & 14
\end{pmatrix}$$

In [8]:
A = np.array([[4, 1],
              [5, -2],
              [2, 3]])
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [9]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])



__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [10]:
def dot(A, B):
    if len(A[0]) == len(B):
        result = [[0 for x in range(len(B[0]))] for y in range(len(A))]
        for x_ in range(len(A)):
            for x__ in range(len(A[0])):
                for y_ in range(len(B[0])):
                    result[x_][y_] = A[x_][x__] * B[x__][y_] + result[x_][y_]
    return result

In [11]:
A = [[1, 7],
     [3, -6],
     [5, -38],
     [-3, 89]]
B = [[0, 5, 3],
    [2, -1, 69]]

In [12]:
np.dot(A, B)

array([[   14,    -2,   486],
       [  -12,    21,  -405],
       [  -76,    63, -2607],
       [  178,  -104,  6132]])

In [13]:
dot(A, B)

[[14, -2, 486], [-12, 21, -405], [-76, 63, -2607], [178, -104, 6132]]

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$




а)$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx \cdot sinx - (-cosx) \cdot cosx = 1$$

б)$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 = 180$$
в треугольной перемножаем главную диагональ

In [14]:
A = np.array([[4, 2, 3],
              [0, 5, 1],
              [0, 0, 9]])
np.linalg.det(A)

180.0

в)$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 
\begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{vmatrix} = 0$$

In [15]:
(5*9-6*8)-2*(4*9-6*7)+3*(4*8-5*7)

0

In [16]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.linalg.det(A)

-9.51619735392994e-16

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   


а) $det(A^{2}) = det(A \cdot A) = det(A) \cdot det(A) = 4 \cdot 4 = 16$;

б) $det(A^{T})= det(A) = 4$;

в) $det(2A) = 2^n \cdot det(A) = 2^n \cdot 4$, где $n$ количество строк матрицы.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = -2 \cdot 
\begin{vmatrix} 
-14 & 6 \\
 7 & 13 
\end{vmatrix} - 7 \cdot 
\begin{vmatrix} 
4 & 6 \\
-3 & 13
\end{vmatrix} + (-3) \cdot 
\begin{vmatrix} 
4 & -14 \\
-3 & 7
\end{vmatrix} =
-2 \cdot (-14 \cdot 13 - 6 \cdot 7) - 7 (4 \cdot 13 - 6 \cdot (-3)) + (-3)\cdot (4 \cdot 7 - (-14)\cdot (-3)) = 0$$
Если определитель матрицы равен нулю, то матрица вырожденная.

In [17]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.linalg.det(A)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

a)$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$$Третья строка = сумме первой и второй строк$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$$
..
$$\begin{pmatrix}
1 & 1 & 1 \\
1 & 2 & 3
\end{pmatrix}$$

вычитаем из второй строки первую

$$\begin{pmatrix}
1 & 1 & 1 \\
0 & 1 & 2
\end{pmatrix}$$
Ранг матрицы $2$.

In [18]:
A = np.array([[1, 2, 3],
              [1, 1, 1],
              [2, 3, 4]])
np.linalg.matrix_rank(A)

2

б)$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$
..
$$\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
0 & 0 & 2 & 1\\ 
\end{pmatrix}$$
делим на 2 первую строку

делим на 2 вторую, 
прибавляем вторую строку помноженную на -4 к третьей строке, 
прибавляем вторую строку помноженную на -2 к четвертой строке

$$\begin{pmatrix}
1 & 1 \frac{1}{2} & 2 \frac{1}{2} & 3\\
0 & 0 & 1 & 1\\ 
0 & 0 & 0 & -1\\ 
0 & 0 & 0 & -1\\ 
\end{pmatrix}$$
..
$$\begin{pmatrix}
1 & 1 \frac{1}{2} & 2 \frac{1}{2} & 3\\
0 & 0 & 1 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & -1\\ 
\end{pmatrix}$$
..
$$\begin{pmatrix}
1 & 1 \frac{1}{2} & 2 \frac{1}{2} & 3\\
0 & 0 & 1 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 0\\ 
\end{pmatrix}$$
Ранг матрицы  $3$.

In [19]:
A = np.array([[0, 0, 2, 1],
              [0, 0, 2, 2],
              [0, 0, 4, 3],
              [2, 3, 5, 6]])

np.linalg.matrix_rank(A)

3