__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$


$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} $$
.
$$(-1-\lambda)(6-\lambda) - (-6)\cdot 2 =0 $$
.
$$\lambda^2 - 5\lambda + 6 = 0$$
.
$$\begin{cases}
     \lambda_1 = 2 \\
     \lambda_2 = 3
\end{cases}$$
.
$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
.
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}
$$
.
$$\begin{cases}
    -x_1 -6x_2 = 2x_1 \\
    2x_1 + 6x_2 = 2x_2
\end{cases}$$
.
$$x_1 = -2x_2$$
.
$$x = \begin{pmatrix}
-2x_2\\ 
x_2
\end{pmatrix}$$
.пусть x2 = 1
$$x = \begin{pmatrix}
-2\\ 
1
\end{pmatrix}$$
.
$$\begin{cases}
    -x_1 -6x_2 = 3x_1 \\
    2x_1 + 6x_2 = 3x_2
\end{cases}$$
.
$$x_1 = -\frac{3}{2}x_2$$
.
$$x = \begin{pmatrix}
-\frac{3}{2}x_2\\ 
x_2
\end{pmatrix}$$
.
$$x = \begin{pmatrix}
-\frac{3}{2}\\ 
1
\end{pmatrix}$$

In [1]:
import numpy as np

In [2]:
A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)

print(f'\n{A}')
print(f'Собственные значения\n{w}')
print(f'Собственные векторы\n{v}')


[[-1 -6]
 [ 2  6]]
Собственные значения
[2. 3.]
Собственные векторы
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]



__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.


$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$
..

$
\lambda=-1
$
.
$$\begin{cases}
-x_{1}+0\cdot x_{2}= -x_{1}, \\
0\cdot x_{1}-x_{2}= -x_{2}.
\end{cases}$$
..
$$\begin{cases}
 - x_{1} = -x_{1}, \\
 - x_{2} = -x_{2}.
\end{cases}$$

In [8]:
A = np.array([[-1, 0],
              [0, -1]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]




__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



$$\begin{cases}
    1 + 1 = \lambda \\
    -1 + 3 = \lambda
\end{cases}$$
..
$$\begin{cases}
    \lambda = 2 \\
    \lambda = 2 
\end{cases}$$


In [3]:
A = np.array([[1, 1],
              [-1, 3]])
v = np.array([[1],
              [1]])
A_2 = np.dot(A, v)
A_2/2

array([[1.],
       [1.]])

(1, 1) собственный вектор

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$\begin{cases}
    0 \cdot 3 + 3 \cdot (-3) + 0\cdot (-4) = 3 \lambda \\
    3 \cdot 3 + 0 \cdot (-3) + 0 \cdot (-4) = -3 \lambda \\
    0 \cdot (3) + 0 \cdot (-3) + 3 \cdot (-4) = -4 \lambda
\end{cases}$$
..
$$\begin{cases}
    -9 = 3 \lambda \\
    9 = -3 \lambda \\
    -12 = -4 \lambda
\end{cases}$$
..
$$\begin{cases}
    \lambda = -3 \\
    \lambda = -3 \\
    \lambda = 3 
\end{cases}$$
нет cходится

In [4]:
A = np.array([[0, 3, 0],
              [3, 0, 0],
              [0, 0, 3]])
v = np.array([[3],
              [-3],
              [-4]])
A_2 = np.dot(A, v)
A_2

array([[ -9],
       [  9],
       [-12]])

In [5]:
A_2/3

array([[-3.],
       [ 3.],
       [-4.]])

In [6]:
A_2/-3

array([[ 3.],
       [-3.],
       [ 4.]])

не является собственным вектором